production: &defaults
  adapter: redis
  url: redis://localhost:6379/1
  timeout: 1

development:
  <<: *defaults
  url: redis://localhost:6379/2

test:
  <<: *defaults
  url: redis://localhost:6379/3
